version: "3.7"
services:
  agora-el-node1:
    container_name: agora-el-node1
    image: bosagora/agora-el-node:v2.0.1
    ports:
      - "8541:8541"
    restart: always
    volumes:
      - ../chain1/node:/data
      - ../chain1/config:/config
    command:
      --config=/config/config.toml
      --datadir=/data
      --syncmode=full
      --gcmode=archive
      --allow-insecure-unlock=true
      --unlock=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --http.corsdomain="*"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
