################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "${HOST_IP}"
    # Port on which we bind (default: 7070)
    port: "${HOST_PORT}"

################################################################################
##                               Database options                             ##
################################################################################
database:
    host: "${DATABASE_HOST}"
    user: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
    database: "${DATABASE_NAME}"
    scheme: "${DATABASE_SCHEME}"
    port: "${DATABASE_PORT}"
    connectionTimeoutMillis: 5000
    max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: verbose

################################################################################
##                             Scheduler options                              ##
################################################################################
scheduler:
    enable: true
    items:
        - name: bridge
          enable: true
          expression: "*/10 * * * * *"

bridge:
    networkAName: "production_main"
    networkABridgeAddress: "0x4Ca91738C7cD24895467c6d550D96BE8dC4b33AA"
    networkATokenAddress: "0xB1A90a5C6e30d64Ab6f64C30eD392F46eDBcb022"
    networkBName: "production_side"
    networkBBridgeAddress: "0xd73e6a2f2e47236F1Ff737E72497f598652122F9"
    networkBTokenAddress: "0xB1A90a5C6e30d64Ab6f64C30eD392F46eDBcb022"
    validators:
        - "${BRIDGE_VALIDATOR1}"
        - "${BRIDGE_VALIDATOR2}"
        - "${BRIDGE_VALIDATOR3}"
