################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "${HOST_IP}"
    # Port on which we bind (default: 7070)
    port: "${HOST_PORT}"

################################################################################
##                               Database options                             ##
################################################################################
database:
    host: "${DATABASE_HOST}"
    user: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
    database: "${DATABASE_NAME}"
    scheme: "${DATABASE_SCHEME}"
    port: "${DATABASE_PORT}"
    connectionTimeoutMillis: 5000
    max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: verbose

################################################################################
##                             Scheduler options                              ##
################################################################################
scheduler:
    enable: true
    items:
        - name: bridge
          enable: true
          expression: "*/10 * * * * *"

bridge:
    networkAName: "production_main"
    networkABridgeAddress: "0x7265F4D550AEdc3Ed97a6ae6dDAf4289eDFaC0C5"
    networkATokenAddress: "0x3A90432BBfd5Bd87788f397F46c24685492fb30E"
    networkBName: "production_side"
    networkBBridgeAddress: "0x6DA3F9D26C5964ab6E3902fFD7907B6bc3465493"
    networkBTokenAddress: "0x3A90432BBfd5Bd87788f397F46c24685492fb30E"
    validators:
        - "${BRIDGE_VALIDATOR1}"
        - "${BRIDGE_VALIDATOR2}"
        - "${BRIDGE_VALIDATOR3}"
