version: "3.7"
services:
  agora-el-node2:
    container_name: agora-el-node2
    image: bosagora/agora-el-node:v2.0.1
    ports:
      - "8542:8542"
    restart: always
    volumes:
      - ../chain2/node:/data
      - ../chain2/config:/config
    command:
      --config=/config/config.toml
      --datadir=/data
      --syncmode=full
      --gcmode=archive
      --allow-insecure-unlock=true
      --unlock=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --http.corsdomain="*"
