name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: agora
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Check formatting of Contract
        run: cd packages/contracts && yarn run formatting:check
      - name: Compile of Contract
        run: cd packages/contracts && yarn run build
      - name: Run Hardhat Tests of Contract
        env:
          REPORT_GAS: true
        run: cd packages/contracts && yarn run test

      - name: Copy env of Validator
        run: cp packages/validator/env/.env.sample packages/validator/env/.env
      - name: Check formatting of Validator
        run: cd packages/validator && yarn run formatting:check
      - name: Compile of Validator
        run: cd packages/validator && yarn run build
      - name: Run Hardhat Tests of Validator
        run: cd packages/validator && yarn run test
